resources:
  - name: gitRepoRes_ben
    type: GitRepo
    configuration:
      gitProvider: log_analytics_splunk_github
      path: benharosh/log-analytics-splunk
      branches:
        include: test
        exclude: master

  - name: image_res_ben
    type: Image
    configuration:
      autoPull: false
      sourceRepository: pts-observability
      registry: PartnershipArtifactory
      imageName: partnership-pts-observability.jfrog.io/fluentd
      imageTag: '4.1.1'

pipelines:
  - name: dockerbuild_fluentd_test
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: DockerBuildAndPush
          dockerFileLocation: fluentd-installer
          dockerFileName: Dockerfile.fluentd.sidecar
          dockerImageName: partnership-pts-observability.jfrog.io/fluentd
          dockerImageTag: '4.1.1'
          inputResources:
            - name: gitRepoRes_ben
          integrations:
            - name: PartnershipArtifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: DockerBuildAndPush
          integrations:
            - name: PartnershipArtifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: image_res_ben